```{r}
#TAREA 5
#Jaime Saul Vicente Maldonado

#1. Left-joining questions and tags+++++++++++++++++++++++++++++++++++++++++++++
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

```{r}
#1.1. Relacione questions y question_tags usando las columnas id y question_id, respectivamente.
library(tidyverse)
library(dplyr)
```

```{r}
#1.2. Agregue una relación más para la tabla tags.
```

```{r}
#1.3. Utilice replace_na para cambiar los NA en la columna tag_name a "only-r"
```

```{r}
#1.4. Por último, almacene el resultado en la variable questions_with_tags.
```

```{r}
#2. Comparing scores across tags++++++++++++++++++++++++++++++++++++++++++++++++
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

```{r}
#2.1. Utilice questions_with_tags y aplique group_by para la variable tag_name.
```

```{r}
#2.2. Aplique summarize para obtener el score promedio de cada pregunta y asígnele el nombre mean_score.
```

```{r}
#2.3. Ordene mean_score en forma descendente.
```

```{r}
#3. Finding gaps between questions and answers++++++++++++++++++++++++++++++++++
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

```{r}
#3.1. Utilice inner_join para combinar las tablas questions y answers, luego aplique los sufijos "_question" y "_answer", respectivamente.
```

```{r}
#3.2. Agregue una nueva columna utilizando la función mutate. La nueva columna se llamará gap y contendrá la resta de creation_date_answer y creation_date_question. (creation_date_answer - creation_date_question).
```

```{r}
#4. Joining question and answer counts++++++++++++++++++++++++++++++++++++++++++
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

```{r}
#4.1. Cuente y ordene la columna question_id en la tabla de answers, luego almacene el resultado en la variable answer_counts.
```

```{r}
#4.2. Relacione la tabla questions con answer_counts (utilice left_join).
```

```{r}
#4.3. Reemplace los valores NA en la columna n con ceros.
```

```{r}
#4.4. Por último almacene el resultado en la variable question_answer_counts
```

```{r}
#5. Joining questions, answers, and tags++++++++++++++++++++++++++++++++++++++++
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

```{r}
#5.1. Combine question_tags con question_answer_counts usando inner_join.
```

```{r}
#5.2. Ahora, use otro inner_join para agregar la tabla tags.
```

